{"name": "test_gerar_token_de_autentica√ß√£o_v√°lido", "status": "failed", "statusDetails": {"message": "AssertionError: ‚ùå Erro ao criar usu√°rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "fixturefunc = <function create_user at 0x10782b060>, request = <FixtureRequest for <Function test_gerar_token_de_autentica√ß√£o_v√°lido>>, kwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.venv/lib/python3.13/site-packages/_pytest/fixtures.py:898: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @given(\"que eu tenho um usu√°rio criado\")\n    def create_user():\n        \"\"\"Cria um usu√°rio antes da autentica√ß√£o\"\"\"\n        logging.info(\"üü¢ [IN√çCIO] Criando Usu√°rio para Autentica√ß√£o\")\n    \n        response = APIClient.create_user(pytest.user_data[\"userName\"], pytest.user_data[\"password\"])\n>       assert response.status_code == 201, f\"‚ùå Erro ao criar usu√°rio: {response.text}\"\nE       AssertionError: ‚ùå Erro ao criar usu√°rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nE       assert 406 == 201\nE        +  where 406 = <Response [406]>.status_code\n\ntests/api/test_auth.py:23: AssertionError"}, "description": "/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/features/api_auth.feature: Gerar token de autentica√ß√£o v√°lido", "attachments": [{"name": "log", "source": "e2361f12-46c8-437f-a7a3-df07b8f50c26-attachment.txt", "type": "text/plain"}], "start": 1739370862526, "stop": 1739370863048, "uuid": "4a920d0d-76df-4348-9288-e84cd47add4f", "historyId": "bd14c6e7f815f15771e997292c67c1f1", "testCaseId": "bd14c6e7f815f15771e997292c67c1f1", "fullName": "tests.api.test_auth#test_gerar_token_de_autentica√ß√£o_v√°lido", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "MacBook-Pro-de-Danilo.local"}, {"name": "thread", "value": "51217-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth"}]}