{"uuid": "06fa20ab-b4ec-4ed3-8a6d-1e5cb69744be", "children": ["568f10b6-123c-4a72-a40a-efd54b190404"], "befores": [{"name": "setup_user", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao criar usuário: {\"code\":\"1204\",\"message\":\"User exists!\"}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code\n", "trace": "  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/conftest.py\", line 21, in setup_user\n    assert response.status_code == 201, f\"Erro ao criar usuário: {response.text}\"\n"}, "start": 1739371022448, "stop": 1739371022989}], "start": 1739371022448, "stop": 1739371023018}