{"uuid": "94f3219a-eec3-4bbe-8e41-3c8ed975a8c0", "children": ["4b03af82-7309-4e6e-8205-41acc5d451e6", "e73dc250-010e-4964-9cf6-80a5b62a397c", "cea5871f-a18b-4388-9fd0-1862124c9b59", "bd022d2e-0ee3-4ffe-8a09-f928b1d30233"], "befores": [{"name": "setup_user", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'token'\n", "trace": "  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/conftest.py\", line 30, in setup_user\n    logging.debug(f\"✅ Usuário criado e autorizado com sucesso. ID: {pytest.user_id}, Token: {pytest.token}\")\n                                                                                              ^^^^^^^^^^^^\n"}, "start": 1739367460337, "stop": 1739367462101}], "start": 1739367460337, "stop": 1739367462146}