[35mDEBUG   [0m root:conftest.py:18 üë§ Criando novo usu√°rio para o teste: usuario_teste_4394
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/Authorized HTTP/1.1" 200 4
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 2c2739ab-041b-4ab9-887d-35e171650af0, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDM5NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzcyOTY4fQ.dt-NQcj4VLHdBveY2q-zfaZFIfYeXUOXNzmIbciI7Tw
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um nome de usu√°rio e uma senha v√°lidos': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um nome de usu√°rio e uma senha v√°lidos' scope='function' baseid='tests/api/test_create_user.py'>]
[32mINFO    [0m root:test_create_user.py:20 üü¢ [IN√çCIO] Gerando Usu√°rio para Teste
[32mINFO    [0m root:test_create_user.py:26 üë§ Usu√°rio Gerado: usuario_teste_9080
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_envio uma requisi√ß√£o para criar um usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_envio uma requisi√ß√£o para criar um usu√°rio' scope='function' baseid='tests/api/test_create_user.py'>]
[32mINFO    [0m root:test_create_user.py:31 üì© Enviando requisi√ß√£o para criar usu√°rio...
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[32mINFO    [0m root:test_create_user.py:35 üì§ Resposta recebida da API: 201 - {"userID":"28c806f0-c1b4-481e-b77b-1d7a41065b97","username":"usuario_teste_9080","books":[]}
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar um status 201': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar um status 201' scope='function' baseid='tests/api/test_create_user.py'>]
[32mINFO    [0m root:test_create_user.py:41 ‚úÖ Usu√°rio criado com sucesso na API!
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_o usu√°rio deve ser criado com sucesso': [<FixtureDef argname='pytestbdd_stepdef_then_o usu√°rio deve ser criado com sucesso' scope='function' baseid='tests/api/test_create_user.py'>]
[32mINFO    [0m root:test_create_user.py:46 üîç Verificando se o usu√°rio foi registrado corretamente...
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "GET /Account/v1/User/28c806f0-c1b4-481e-b77b-1d7a41065b97 HTTP/1.1" 200 92
[35mDEBUG   [0m root:api_client.py:35 üì• Resposta da API ao obter detalhes do usu√°rio: 200 - {"userId":"28c806f0-c1b4-481e-b77b-1d7a41065b97","username":"usuario_teste_9080","books":[]}
[32mINFO    [0m root:test_create_user.py:59 ‚úÖ Usu√°rio registrado com sucesso na API!