{"name": "test_gerar_token_de_autenticação_válido", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable", "trace": "fixturefunc = <function verify_auth_token at 0x105137600>, request = <FixtureRequest for <Function test_gerar_token_de_autenticação_válido>>, kwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\n.venv/lib/python3.13/site-packages/_pytest/fixtures.py:898: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @then(\"a API deve retornar um token de autenticação\")\n    def verify_auth_token():\n        \"\"\"Verifica se a autenticação foi bem-sucedida e o token foi gerado\"\"\"\n        assert pytest.response.status_code == 200, f\"❌ Erro na autenticação: {json.dumps(pytest.response.json(), indent=4)}\"\n    \n        response_json = pytest.response.json()\n        assert \"token\" in response_json, \"❌ Erro: Token não encontrado na resposta\"\n    \n        pytest.token = response_json[\"token\"]\n>       logging.info(f\"✅ Token de autenticação gerado com sucesso: {pytest.token[:20]}...\")\nE       TypeError: 'NoneType' object is not subscriptable\n\ntests/api/test_auth.py:59: TypeError"}, "description": "/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/features/api_auth.feature: Gerar token de autenticação válido", "attachments": [{"name": "log", "source": "ed7820d4-561c-4eb2-898c-f05aee6487ed-attachment.txt", "type": "text/plain"}], "start": 1739372804957, "stop": 1739372807301, "uuid": "eea0ce06-949a-45c0-a4fa-78935ca892ab", "historyId": "bd14c6e7f815f15771e997292c67c1f1", "testCaseId": "bd14c6e7f815f15771e997292c67c1f1", "fullName": "tests.api.test_auth#test_gerar_token_de_autenticação_válido", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "MacBook-Pro-de-Danilo.local"}, {"name": "thread", "value": "51778-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth"}]}