[35mDEBUG   [0m root:conftest.py:14 üë§ Criando usu√°rio de teste: usuario_teste_4254
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_4254
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g","expires":"2025-02-19T13:56:06.445Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 8370e4f8-cf7c-45fd-a8f5-f8499a4cf145, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g
[35mDEBUG   [0m root:conftest.py:43 üîç Antes do teste: Token Atual = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_envio uma requisi√ß√£o para autenticar o usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_envio uma requisi√ß√£o para autenticar o usu√°rio' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_3836
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfMzgzNiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY4fQ.gVRY3-yEEEisW8M3Lj7rcK7ZilYKywsNWWGJ7EVwDOI","expires":"2025-02-19T13:56:08.056Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfMzgzNiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY4fQ.gVRY3-yEEEisW8M3Lj7rcK7ZilYKywsNWWGJ7EVwDOI
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar um token de autentica√ß√£o': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar um token de autentica√ß√£o' scope='function' baseid='tests/api/test_auth.py'>]