{"name": "test_validar_alerta", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_user():\n        \"\"\"Cria um novo usu치rio para cada teste e gera um novo token\"\"\"\n        user_data = {\n            \"userName\": generate_username(),\n            \"password\": get_default_password()\n        }\n        logging.debug(f\"游녻 Criando novo usu치rio para o teste: {user_data['userName']}\")\n    \n        response = APIClient.create_user(user_data[\"userName\"], user_data[\"password\"])\n>       assert response.status_code == 201, f\"Erro ao criar usu치rio: {response.text}\"\nE       AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nE       assert 406 == 201\nE        +  where 406 = <Response [406]>.status_code\n\nconftest.py:23: AssertionError"}, "description": "../../features/ui_alerts.feature: Validar exibi칞칚o de alerta", "start": 1739404348307, "stop": 1739404348307, "uuid": "a9e7a351-e19b-4bd0-9205-1bf6d0bf979e", "historyId": "3b29868cdfcbe06c15fa57cb959b87b4", "testCaseId": "3b29868cdfcbe06c15fa57cb959b87b4", "fullName": "tests.ui.test_alerts#test_validar_alerta", "labels": [{"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_alerts"}, {"name": "host", "value": "MacBook-Pro-de-Danilo.local"}, {"name": "thread", "value": "61967-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_alerts"}]}