[35mDEBUG   [0m root:conftest.py:43 üîç Antes do teste: Token Atual = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que estou autenticado na API': [<FixtureDef argname='pytestbdd_stepdef_given_que estou autenticado na API' scope='function' baseid='tests/api/test_reservation.py'>]
[35mDEBUG   [0m root:test_reservation.py:13 üîê Verificando autentica√ß√£o do usu√°rio... ID: 0d374e1e-47c8-4640-9623-414e2c8a4442, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTY2fQ.pYzAO0necGNBSPaJ8lGzfKdjOL5MUq7AhBKSmes7o3g
[35mDEBUG   [0m root:api_client.py:59 üîç Verificando se o usu√°rio 0d374e1e-47c8-4640-9623-414e2c8a4442 est√° autorizado...
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "GET /Account/v1/User/0d374e1e-47c8-4640-9623-414e2c8a4442 HTTP/1.1" 401 48
[35mDEBUG   [0m root:api_client.py:61 üì• Resposta da API: 401 - {"code":"1200","message":"User not authorized!"}
[35mDEBUG   [0m root:test_reservation.py:19 üîÑ Token inv√°lido. Tentando regenera√ß√£o...
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_4254
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTcwfQ.wsRPz5jp_4rHaHWfY1fK7nZUS8T04SUy7NpjN8ffnCQ","expires":"2025-02-19T13:56:10.799Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTcwfQ.wsRPz5jp_4rHaHWfY1fK7nZUS8T04SUy7NpjN8ffnCQ
[35mDEBUG   [0m root:test_reservation.py:32 ‚úÖ Novo Token Gerado: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNDI1NCIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NTcwfQ.wsRPz5jp_4rHaHWfY1fK7nZUS8T04SUy7NpjN8ffnCQ
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "GET /Account/v1/User/0d374e1e-47c8-4640-9623-414e2c8a4442 HTTP/1.1" 401 48
[35mDEBUG   [0m root:test_reservation.py:39 ‚ùå O ID do usu√°rio pode estar incorreto ap√≥s a regenera√ß√£o do token.