{"uuid": "f0390d80-adf6-4d77-9719-ac4b5fb53817", "children": ["d77fa2ea-1ac2-45b5-80dc-a305873aee53"], "befores": [{"name": "debug_token", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'token'\n", "trace": "  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/conftest.py\", line 35, in debug_token\n    logging.debug(f\"üîç Antes do teste: Token Atual = {pytest.token}\")\n                                                      ^^^^^^^^^^^^\n"}, "start": 1739368526244, "stop": 1739368526244}], "start": 1739368526244, "stop": 1739368526245}