{"uuid": "113c8cc0-19bc-4ddd-a77d-67202362e57b", "children": ["465332dd-dca5-4793-b65c-a7d3fbc6a771"], "befores": [{"name": "debug_token", "status": "broken", "statusDetails": {"message": "AttributeError: module 'pytest' has no attribute 'token'\n", "trace": "  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/conftest.py\", line 35, in debug_token\n    logging.debug(f\"üîç Antes do teste: Token Atual = {pytest.token}\")\n                                                      ^^^^^^^^^^^^\n"}, "start": 1739368483171, "stop": 1739368483171}], "start": 1739368483171, "stop": 1739368483173}