[35mDEBUG   [0m root:conftest.py:14 üë§ Criando usu√°rio de teste: usuario_teste_7066
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_7066
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzA2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgwfQ.H6tScb51v5oh-k28EjUjWOUb-8LDtUN11GiQ82xxTnE","expires":"2025-02-19T13:59:40.161Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzA2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgwfQ.H6tScb51v5oh-k28EjUjWOUb-8LDtUN11GiQ82xxTnE
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: ec8fde41-fadb-4def-a785-b7ac72a2c82e, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzA2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgwfQ.H6tScb51v5oh-k28EjUjWOUb-8LDtUN11GiQ82xxTnE
[35mDEBUG   [0m root:conftest.py:43 üîç Antes do teste: Token Atual = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzA2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgwfQ.H6tScb51v5oh-k28EjUjWOUb-8LDtUN11GiQ82xxTnE
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_envio uma requisi√ß√£o para autenticar o usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_envio uma requisi√ß√£o para autenticar o usu√°rio' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_3166
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfMzE2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgxfQ.mqVkJuoqUscDZvydvpOi_HgZvnSJgsNdcx-jPG9Asnw","expires":"2025-02-19T13:59:41.728Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfMzE2NiIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY4NzgxfQ.mqVkJuoqUscDZvydvpOi_HgZvnSJgsNdcx-jPG9Asnw
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar um token de autentica√ß√£o': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar um token de autentica√ß√£o' scope='function' baseid='tests/api/test_auth.py'>]