[35mDEBUG   [0m root:conftest.py:18 üë§ Criando novo usu√°rio para o teste: usuario_teste_6209
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/Authorized HTTP/1.1" 200 4
[35mDEBUG   [0m root:conftest.py:36 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 40d2cf41-0459-423c-b467-ecd8f5b43afc, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNjIwOSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzcwODYxfQ.vOcCKvf_MZ6Ej4R3rt9L9nUp2vdFFWBOCO99MXyePwg
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado' scope='function' baseid='tests/api/test_auth.py'>]
[32mINFO    [0m root:test_auth.py:20 üü¢ [IN√çCIO] Criando Usu√°rio para Autentica√ß√£o
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 406 40