[35mDEBUG   [0m root:conftest.py:14 üë§ Criando usu√°rio de teste: usuario_teste_6585
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_6585
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNjU4NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzE5fQ.eT-VeVX4cmOeFs_dEajw7IGvLgVqKZTaRn-xKnPtoKY","expires":"2025-02-19T13:25:19.261Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNjU4NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzE5fQ.eT-VeVX4cmOeFs_dEajw7IGvLgVqKZTaRn-xKnPtoKY
[35mDEBUG   [0m root:conftest.py:29 ‚úÖ Usu√°rio criado e autorizado com sucesso. ID: 6ec3a246-9f06-4e65-b2e8-c986c400de90, Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNjU4NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzE5fQ.eT-VeVX4cmOeFs_dEajw7IGvLgVqKZTaRn-xKnPtoKY
[35mDEBUG   [0m root:conftest.py:36 üîç Antes do teste: Token Atual = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNjU4NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzE5fQ.eT-VeVX4cmOeFs_dEajw7IGvLgVqKZTaRn-xKnPtoKY
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_given_que eu tenho um usu√°rio criado': [<FixtureDef argname='pytestbdd_stepdef_given_que eu tenho um usu√°rio criado' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/User HTTP/1.1" 201 92
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_when_envio uma requisi√ß√£o para autenticar o usu√°rio': [<FixtureDef argname='pytestbdd_stepdef_when_envio uma requisi√ß√£o para autenticar o usu√°rio' scope='function' baseid='tests/api/test_auth.py'>]
[35mDEBUG   [0m root:api_client.py:20 üì§ Gerando token para usu√°rio: usuario_teste_7665
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): demoqa.com:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:544 https://demoqa.com:443 "POST /Account/v1/GenerateToken HTTP/1.1" 200 288
[35mDEBUG   [0m root:api_client.py:24 üì• Resposta da API ao gerar token: 200 - {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzY2NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzIwfQ.Gxeha1kM5lRy_1KOUNe6m8fgsULjce-V9vgsqpndGeU","expires":"2025-02-19T13:25:20.758Z","status":"Success","result":"User authorized successfully."}
[35mDEBUG   [0m root:api_client.py:29 ‚úÖ Token gerado com sucesso: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InVzdWFyaW9fdGVzdGVfNzY2NSIsInBhc3N3b3JkIjoiVGVzdGVAMTIzIiwiaWF0IjoxNzM5MzY2NzIwfQ.Gxeha1kM5lRy_1KOUNe6m8fgsULjce-V9vgsqpndGeU
[35mDEBUG   [0m pytest_bdd.scenario:scenario.py:150 Adding providers for fixture 'pytestbdd_stepimpl_then_a API deve retornar um token de autentica√ß√£o': [<FixtureDef argname='pytestbdd_stepdef_then_a API deve retornar um token de autentica√ß√£o' scope='function' baseid='tests/api/test_auth.py'>]